export const INCREASE_OUR_SCORE = 'INCREASE_OUR_SCORE';

export const DECREASE_OUR_SCORE = 'DECREASE_OUR_SCORE';

export const INCREASE_THEIR_SCORE = 'INCREASE_THEIR_SCORE';

export const DECREASE_THEIR_SCORE = 'DECREASE_THEIR_SCORE';

export const TOGGLE_SCORE_MODAL = 'TOGGLE_SCORE_MODAL';

export const TOGGLE_SUB_MODAL = 'TOGGLE_SUB_MODAL';

export const TOGGLE_STAT_MODAL = 'TOGGLE_STAT_MODAL';

export const SUBSTITUTE_PLAYER = 'SUBSTITUTE_PLAYER';
